import type { ImageSourcePropType } from 'react-native';
const IMAGES: Record<string, ImageSourcePropType> = {
  'real-madrid': require('./indices/real-madrid.png'),
  'fcb-icon': require('./indices/fcb-icon.png'),
  'manchester-united': require('./indices/manchester-united.png'),
  'psg': require('./indices/psg.png'),
  'manchester-city': require('./indices/manchester-city.png'),
  'liverpool-crest': require('./indices/liverpool-crest.png'),
  'juventus': require('./indices/juventus.png'),
  'bayern': require('./indices/bayern.png'),
  'chelsea': require('./indices/chelsea.png'),
  'arsenal': require('./indices/arsenal.png'),
  'tottenham': require('./indices/tottenham.png'),
  'atletico': require('./indices/atletico.png'),
  'inter-milan': require('./indices/inter-milan.png'),
  'ac-milan': require('./indices/ac-milan.png'),
  'dortmund': require('./indices/dortmund.png'),
  'lamine-profile': require('./indices/lamine-avatar-v2.jpg'),
  'kylian-mbappe': require('./indices/mbappe-avatar-v2.jpg'),
  'dembele-profile': require('./indices/dembele-profile.jpg'),
  'raphinha-profile': require('./indices/raphinha-profile.jpg'),
  'erling-haaland': require('./indices/haaland-avatar-v2.jpg'),
  'kane-profile': require('./indices/kane-profile.jpg'),
  'vinicius-junior': require('./indices/vinicius-avatar-v2.jpg'),
  'jude-bellingham': require('./indices/bellingham-avatar-v2.jpg'),
  'olise-profile': require('./indices/olise-profile.jpg'),
  'bruno-profile': require('./indices/bruno-profile.jpg'),
  'rodri-profile': require('./indices/rodri-profile.jpg'),
  'osimhen-profile': require('./indices/osimhen-profile.jpg'),
  'musiala-profile': require('./indices/musiala-profile.jpg'),
  'saka-profile': require('./indices/saka-profile.jpg'),
  'palmer-profile': require('./indices/palmer-profile.jpg'),
};
export function marketImage(assetKey: string) { return IMAGES[assetKey]; }
